# Generated by Django 5.1.3 on 2024-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_coursematerial_alter_writingsubmission_grade_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsubmission',
            name='submission_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
