# Generated by Django 5.1.3 on 2024-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_writingsubmission_submission_image_delete_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingsubmission',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='writingsubmission',
            name='submission_image',
        ),
        migrations.RemoveField(
            model_name='writingsubmission',
            name='submission_text',
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='grade',
            field=models.FloatField(),
        ),
    ]
