# Generated by Django 5.1.3 on 2024-12-02 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_writingsubmission_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsubmission',
            name='submission_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
