# Generated by Django 5.1.3 on 2024-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_writingsubmission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsubmission',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
