# Generated by Django 5.1.3 on 2024-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_writingsubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsubmission',
            name='corrected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='corrections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='image',
            field=models.ImageField(default='', upload_to='submissions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
